[build-system]
requires = [ "poetry-core>=1.9.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "flext-cli"
version = "0.9.0"
description = "FLEXT CLI - Developer Command Line Interface"
